# Generated by Django 4.2.11 on 2024-06-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='amount_clients',
            field=models.IntegerField(verbose_name='Количество клиентов'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_creation',
            field=models.DateField(auto_created=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='hotel_services',
            field=models.CharField(max_length=255, verbose_name='Услуги'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('готовится', 'Готовится'), ('готов', 'Готов')], max_length=255, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('принят', 'Принят'), ('оплачен', 'Оплачен')], max_length=255, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='room_number',
            field=models.CharField(max_length=255, verbose_name='Номер комнаты'),
        ),
    ]
