# Generated by Django 4.2.11 on 2024-06-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_order_options_alter_order_amount_clients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_creation',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
