# Generated by Django 4.2.11 on 2024-06-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_order_date_creation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderuserlist',
            options={'verbose_name': 'Связанный заказ', 'verbose_name_plural': 'Связанные заказы'},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'verbose_name': 'Смена', 'verbose_name_plural': 'Смены'},
        ),
        migrations.AlterModelOptions(
            name='userlist',
            options={'verbose_name': 'Связанная смена', 'verbose_name_plural': 'Связанные смены'},
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('готовится', 'Готовится'), ('готов', 'Готов')], default='готовиться', max_length=255, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('принят', 'Принят'), ('оплачен', 'Оплачен')], default='принят', max_length=255, verbose_name='Статус оплаты'),
        ),
    ]
