# Generated by Django 5.0.6 on 2024-06-19 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('cooker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooker_orders', to=settings.AUTH_USER_MODEL)),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiter_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
