# Generated by Django 4.2.11 on 2024-06-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='123', max_length=255),
            preserve_default=False,
        ),
    ]
